### ISSUE TITLE
Wrong documentation of cur_timestamp()

### ISSUE THREAD

**Issue by a-andre** [eulynx-live/rasta-protocol#18]
`cur_timestamp()` returns the time in milliseconds (not seconds). And the time is not necessarily since 1970, compare documentation of `CLOCK_MONOTONIC`.

https://github.com/eulynx-live/rasta-protocol/blob/main/src/c/retransmission/protocol.c#L7-L27

**Comment by laugengebaeck** [comment]
Thanks for spotting this! Will be addressed together with #26.

**Comment by laugengebaeck** [comment]
Fixed this now! Thanks!
