### ISSUE TITLE
Unit tests for the transport layer

### ISSUE THREAD

**Issue by rs22** [eulynx-live/rasta-protocol#25]
There is a common interface for the transport implementations.

Basic unit tests for the specific implementations should be created. 
They should serve as a documentation of the `transport_socket`, `transport_channel` object lifecycles.

**Comment by laugengebaeck** [comment]
I'm not really sure whether this is even possible, because these transport implementations use the socket API, which is very hard (or even impossible) to mock, I guess.

**Comment by rs22** [comment]
hmmm, seems it is at least not impossible: https://stackoverflow.com/questions/44073243/how-to-mock-socket-in-c

Also without mocking, we could test everything except for accept / connect, right?

I.e. the flow of transport_init, transport_create_socket, transport_close_socket (if such a function exists) and then make sure that the event pointers and data structures are set up correctly and reset to a well defined state afterwards...

**Comment by laugengebaeck** [comment]
We should then also extend the `CMakeLists.txt`, so that it doesn't only test the UDP transport implementation.
