### ISSUE TITLE
Cleanup code

### ISSUE THREAD

**Issue by rs22** [eulynx-live/rasta-protocol#26]
- Remove commented code
- Remove code duplication
- Improve documentation and have consistent naming conventions

**Comment by laugengebaeck** [comment]
Partly addressed in #31, but commented code is still a problem. Ideally, @rs22 and me should take one or two hours to go through all of that code and decide if it can be removed.

Code duplication is not that easy to fix in a programming language that does not know about OOP.

Documentation and naming will be improved for the public API in #32.

**Comment by laugengebaeck** [comment]
Further TODO: Check for all functions whether they're declared in the same header as the .c file they're implemented in (or if there's a good reason why they're not). Example: `data_send_event` is declared in `events.h`, but implemented in `rasta.c`.

**Comment by laugengebaeck** [comment]
Closed in favour of smaller refactoring issues, because the big problems regarding code quality are now mostly solved. If there's time available, it would be a good idea to clean up the commented out code.
