### ISSUE TITLE
Cleanup documentation

### ISSUE THREAD

**Issue by laugengebaeck** [eulynx-live/rasta-protocol#48]
In #45, we add a Github Actions workflow that publishes our documentation on Github Pages. To make this as helpful as possible for our users, we should clean up the documentation comments a bit:

- all parameters and the return value of documented functions should be documented
- Doxygen does not show newlines in comments, so we should add some punctuation instead
- if there is time left: document more (ideally all) functions in the public headers

**Comment by rs22** [comment]
Also the user guides references from the README are outdated:

 - Explain the use of rcat examples, remove outdated / non-existing ones
 - Explain how to use the rasta_grpc_bridge
 - Explain how to compile using CMake (docs still talk about gradle)

**Comment by laugengebaeck** [comment]
> Also the user guides references from the README are outdated:

I'm already working on this, will open a PR soon :)
